"""PDF assembly.

Interleaves slide images with the transcript text spoken while each slide was
on screen, so the reader sees what the audience saw at the moment the words
were said.
"""

from __future__ import annotations

import logging
from typing import List, Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_JUSTIFY
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader
from reportlab.platypus import (
    Image,
    ListFlowable,
    ListItem,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

log = logging.getLogger(__name__)

ACCENT = colors.HexColor("#1F4E5F")
MUTED = colors.HexColor("#6B7280")
RULE = colors.HexColor("#D9DEE3")


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "SSTitle", parent=base["Title"], fontSize=24, leading=29,
            textColor=ACCENT, spaceAfter=6,
        ),
        "subtitle": ParagraphStyle(
            "SSSubtitle", parent=base["Normal"], fontSize=10.5, leading=15,
            textColor=MUTED, spaceAfter=18,
        ),
        "h2": ParagraphStyle(
            "SSH2", parent=base["Heading2"], fontSize=14, leading=18,
            textColor=ACCENT, spaceBefore=16, spaceAfter=8,
        ),
        "slide": ParagraphStyle(
            "SSSlide", parent=base["Heading3"], fontSize=12.5, leading=16,
            textColor=ACCENT, spaceBefore=4, spaceAfter=2,
        ),
        "stamp": ParagraphStyle(
            "SSStamp", parent=base["Normal"], fontSize=8.5, leading=11,
            textColor=MUTED, spaceAfter=8,
        ),
        "body": ParagraphStyle(
            "SSBody", parent=base["BodyText"], fontSize=10, leading=15.5,
            alignment=TA_JUSTIFY, spaceAfter=7,
        ),
        "bullet": ParagraphStyle(
            "SSBullet", parent=base["BodyText"], fontSize=10, leading=15,
            spaceAfter=3,
        ),
    }


def _escape(text: str) -> str:
    return (
        text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    )


def _fitted_image(path: str, max_w: float, max_h: float) -> Optional[Image]:
    """Scale a slide image to fit the frame while preserving aspect ratio."""
    try:
        iw, ih = ImageReader(path).getSize()
    except Exception as exc:  # noqa: BLE001
        log.warning("Could not read image %s: %s", path, exc)
        return None
    scale = min(max_w / iw, max_h / ih)
    return Image(path, width=iw * scale, height=ih * scale)


def _clock(seconds: float) -> str:
    m, s = divmod(int(seconds), 60)
    h, m = divmod(m, 60)
    return f"{h:d}:{m:02d}:{s:02d}" if h else f"{m:d}:{s:02d}"


def _segments_between(segments, start: float, end: Optional[float]):
    end = end if end is not None else float("inf")
    return [s for s in segments if start <= s.start < end]


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setStrokeColor(RULE)
    canvas.setLineWidth(0.5)
    canvas.line(0.9 * inch, 0.72 * inch, LETTER[0] - 0.9 * inch, 0.72 * inch)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUTED)
    canvas.drawString(0.9 * inch, 0.55 * inch, "Generated by SlideScribe")
    canvas.drawRightString(LETTER[0] - 0.9 * inch, 0.55 * inch, f"Page {doc.page}")
    canvas.restoreState()


def build_pdf(
    output_path: str,
    title: str,
    segments: List,
    slides: List,
    summary: Optional[dict] = None,
    cleaned_text: Optional[str] = None,
    meta: Optional[dict] = None,
) -> str:
    """Write the illustrated transcript.

    Args:
        output_path: Destination .pdf path.
        title: Document title.
        segments: Transcript segments with ``start``/``end``/``text``.
        slides: Captured slides with ``timestamp``/``image_path``/``title``.
        summary: Optional dict from ``LLMClient.summarize``.
        cleaned_text: Optional LLM-cleaned transcript, used when no slides
            were detected and the document is text-only.
        meta: Optional key/value pairs shown under the title.

    Returns:
        The output path.
    """
    st = _styles()
    doc = SimpleDocTemplate(
        output_path,
        pagesize=LETTER,
        leftMargin=0.9 * inch,
        rightMargin=0.9 * inch,
        topMargin=0.85 * inch,
        bottomMargin=0.95 * inch,
        title=title,
        author="SlideScribe",
    )
    frame_w = doc.width
    story = []

    story.append(Paragraph(_escape(title), st["title"]))
    if meta:
        line = "  ·  ".join(f"{k}: {v}" for k, v in meta.items())
        story.append(Paragraph(_escape(line), st["subtitle"]))

    if summary and summary.get("summary"):
        story.append(Paragraph("Summary", st["h2"]))
        story.append(Paragraph(_escape(summary["summary"]), st["body"]))

        if summary.get("key_points"):
            story.append(Paragraph("Key points", st["h2"]))
            story.append(
                ListFlowable(
                    [
                        ListItem(Paragraph(_escape(p), st["bullet"]))
                        for p in summary["key_points"]
                    ],
                    bulletType="bullet",
                    leftIndent=14,
                )
            )

        if summary.get("action_items"):
            story.append(Paragraph("Action items", st["h2"]))
            story.append(
                ListFlowable(
                    [
                        ListItem(Paragraph(_escape(a), st["bullet"]))
                        for a in summary["action_items"]
                    ],
                    bulletType="bullet",
                    leftIndent=14,
                )
            )
        story.append(PageBreak())

    story.append(Paragraph("Transcript", st["h2"]))

    if not slides:
        text = cleaned_text or " ".join(s.text for s in segments)
        for para in text.split("\n\n"):
            if para.strip():
                story.append(Paragraph(_escape(para.strip()), st["body"]))
        doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
        log.info("Wrote %s (no slides detected)", output_path)
        return output_path

    # Anything spoken before the first slide appears.
    preamble = [s for s in segments if s.start < slides[0].timestamp]
    if preamble:
        story.append(
            Paragraph(_escape(" ".join(s.text for s in preamble)), st["body"])
        )

    for i, slide in enumerate(slides):
        heading = slide.title or f"Slide {i + 1}"
        story.append(Paragraph(_escape(f"{i + 1}. {heading}"), st["slide"]))
        story.append(Paragraph(_clock(slide.timestamp), st["stamp"]))

        img = _fitted_image(slide.image_path, frame_w, 4.1 * inch)
        if img:
            story.append(img)
            story.append(Spacer(1, 9))

        spoken = _segments_between(segments, slide.timestamp, slide.end_timestamp)
        if spoken:
            story.append(
                Paragraph(_escape(" ".join(s.text for s in spoken)), st["body"])
            )
        else:
            story.append(Paragraph("<i>No speech during this slide.</i>", st["stamp"]))

        story.append(Spacer(1, 10))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    log.info("Wrote %s (%d slides, %d segments)", output_path, len(slides), len(segments))
    return output_path
